//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by KungfuMotion.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_MARKERTREE                  101
#define TRC_TYPE                        102
#define NOTHING                         103
#define ID_PROGRESSBAR                  104
#define ID_MOTION_PREVIEW_SCREEN        105
#define BVH_TYPE                        106
#define UNKNOWN_TYPE                    107
#define BLENDING_DLG                    108
#define EXAGGERATING_DLG                109
#define TRANSITING_DLG                  110
#define REPLACING_DLG                   111
#define ID_MOTION_EXTRACTION_SCREEN     112
#define ID_MOTION_WARPING_SCREEN        113
#define ID_MOTION_WARPING               113
#define ID_SNAPSHOT_SCREEN              114
#define IDR_MAINFRAME                   128
#define IDR_KUNGFUTYPE                  129
#define IDI_FIGHT                       132
#define IDI_LOGO                        133
#define IDD_PREVIEW_DIALOG              150
#define IDD_BLENDING_OPTION_DIALOG      151
#define IDI_JOINT                       152
#define IDI_CURVE                       153
#define IDI_ENDSITE                     154
#define IDI_MOTION                      155
#define IDD_DOUBLESCREEN_DIALOG         156
#define IDI_SELECTED                    160
#define IDD_EXTRACT_DIALOG              161
#define IDD_WARPING_DIALOG              162
#define IDD_SNAPSHOT_DIALOG             163
#define IDI_JOINT_1                     165
#define IDD_FILTER_DIALOG               166
#define IDC_FRAMESILDER                 1000
#define IDC_PREVIEW_PLAY                1001
#define IDC_PREVIEW_STOP                1002
#define IDC_PREVIEW_PAUSE               1003
#define IDC_MOTION_PREVIEW_SCREEN_BORDER 1004
#define IDC_MARKERSIZESILDER            1005
#define IDC_BLENDINGVALUE_SLIDER        1006
#define IDC_STARTFRAME_SLIDER           1007
#define IDC_ENDFRAME_SLIDER             1008
#define IDC_MOTIONNAME_TEXTBOX          1009
#define IDC_SCREEN1_BORDER              1010
#define IDC_SCREEN2_STARTFRAME_SLIDER   1012
#define IDC_SCREEN1_STARTFRAME_SLIDER   1013
#define IDC_RADIUS1_SLIDER              1014
#define IDC_RADIUS2_SLIDER              1015
#define IDC_SCREEN1_ENDFRAME_SLIDER     1016
#define IDC_SCREEN2_ENDFRAME_SLIDER     1017
#define IDC_MARKERTREE_DOUBLESCREEN     1018
#define IDC_SELECTEDMARKERLIST          1019
#define IDC_SELECTION_BUTTON_DOUBLESCREEN 1020
#define IDC_SIMVAL_SLIDER               1021
#define IDC_SCREEN2_BORDER              1022
#define IDC_SKETELON_BUTTON             1023
#define IDC_JOINT_BUTTON                1024
#define IDC_DESELECTION_BUTTON_DOUBLESCREEN 1025
#define IDC_SimVal                      1026
#define IDC_S1_STARTFRAME_STATIC        1027
#define IDC_S1_ENDFRAME_STATIC          1028
#define IDC_S2_STARTFRAME_STATIC        1029
#define IDC_S2_ENDFRAME_STATIC          1030
#define IDC_S1_MARKERSIZE_STATIC        1031
#define IDC_S2_MARKERSIZE_STATIC        1032
#define IDC_SELECTIONALL_BUTTON_DOUBLESCREEN 1033
#define IDC_DESELECTIONALL_BUTTON_DOUBLESCREEN 1034
#define IDC_SIMVAL_STATIC               1035
#define IDC_STARTFRAME_EXTRACTION_SLIDER 1036
#define IDC_ENDFRAME_EXTRACTION_SLIDER  1037
#define IDC_STARTFRAME_EXTRACTION_STATIC 1038
#define IDC_ENDFRAME_EXTRACTION_STATIC  1039
#define IDC_SCREEN_EXTRACTION_BORDER    1040
#define IDC_MOTIONNAME_EXTRACTION_TEXTBOX 1041
#define IDC_MARKERSIZE_EXTRACTION_SLIDER 1042
#define IDC_MARKERSIZE_EXTRACTION_STATIC 1043
#define IDC_WARPING_BORDER              1044
#define IDC_FRAME_WARPING_SLIDER        1045
#define IDC_DURATION_TEXTBOX            1046
#define IDC_FPS_TEXTBOX                 1047
#define IDC_MARKERSIZE_WARPING_SLIDER   1048
#define IDC_MOTIONNAME_WARPING_TEXTBOX  1049
#define IDC_ORIGINALDURATION_WARPING_STATIC 1050
#define IDC_SAVE_SNAPSHOT_BUTTON        1055
#define IDC_TIME_SNAPSHOT_TEXTBOX       1056
#define IDC_MOTIONTREE_SNAPSHOT_TREE    1057
#define IDC_SNAPSHOT_BORDER             1058
#define IDC_SHOW_SNAPSHOT_BUTTON        1059
#define IDC_FRAME_SNAPSHOT_SLIDER       1060
#define IDC_MARKERSIZE_SNAPSHOT_SLIDER  1061
#define IDC_IGNORESIGN_FILTER_CHECK     1064
#define IDC_TOLERANCE_FILTER_EDIT       1065
#define IDC_MOTIONNAME_FILTER_STATIC    1066
#define IDC_CURVENAME_FILTER_STATIC     1067
#define IDC_MARKERNAMESTATIC            1068
#define ID_HELP_HELP                    32771
#define ID_FILE_NEW_PROJECT             32772
#define ID_FILE_OPEN_PROJECT            32773
#define ID_FILE_CLOSE_PROJECT           32774
#define ID_APP_ABOUT_KUNGFU_MOTION      32775
#define ID_FILE_SAVE_PROJECT            32776
#define ID_FILE_SAVE_PROJECT_AS         32777
#define ID_FILE_IMPORT                  32778
#define ID_FILE_EXPORT                  32779
#define ID_VIEW_MOVE                    32780
#define ID_VIEW_ZOOM_IN                 32781
#define ID_VIEW_ZOOM_OUT                32782
#define ID_TOOL_SELECT_CURVE            32783
#define ID_CURVE_SELECT_CURVE           32783
#define ID_TOOL_SELECT_POINT            32784
#define ID_CURVE_SELECT_POINT           32784
#define ID_TOOL_INSERT_POINT            32785
#define ID_CURVE_INSERT_POINT           32785
#define ID_TOOL_DELETE_POINT            32786
#define ID_CURVE_DELETE_POINT           32786
#define ID_TOOL_MERGE_POINT             32787
#define ID_CURVE_MERGE_POINT            32787
#define ID_TOOL_SPLIT_POINT             32788
#define ID_CURVE_SPLIT_POINT            32788
#define ID_TOOL_FLATTEN                 32789
#define ID_CURVE_FLATTEN                32789
#define ID_TOOL_SHARPEN                 32790
#define ID_CURVE_SHARPEN                32790
#define ID_TOOL_SINGLE_TANGENT          32791
#define ID_CURVE_SINGLE_TANGENT         32791
#define ID_TOOL_DOUBLE_TANGENT          32792
#define ID_CURVE_DOUBLE_TANGENT         32792
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_BUTTON32795                  32795
#define ID_BUTTON32796                  32796
#define ID_BUTTON32797                  32797
#define ID_BUTTON32798                  32798
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_BUTTON32805                  32805
#define ID_VIEW_RESET                   32806
#define ID_BUTTON32807                  32807
#define ID_MOTION_PREVIEW               32810
#define ID_MOTION_BLENDING              32811
#define ID_VIEW_CP                      32812
#define ID_VIEW_PP                      32813
#define ID_VIEW_IP                      32814
#define ID_CURVE_FIT                    32816
#define ID_MOTION_EXAGGERATING          32817
#define ID_MOTION_TRANSITION            32818
#define ID_MOTION_REPLACING             32819
#define ID_MOTION_EXTRACTING            32820
#define ID_FILE_SAVESNAPSHOT            32821
#define ID_MOTION_FILTER                32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
